# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sapsey/Documents/compiler-final-haskell

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sapsey/Documents/compiler-final-haskell

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sapsey/Documents/compiler-final-haskell/CMakeFiles /home/sapsey/Documents/compiler-final-haskell/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sapsey/Documents/compiler-final-haskell/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named compiler_final_haskell

# Build rule for target.
compiler_final_haskell: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 compiler_final_haskell
.PHONY : compiler_final_haskell

# fast build rule for target.
compiler_final_haskell/fast:
	$(MAKE) -f CMakeFiles/compiler_final_haskell.dir/build.make CMakeFiles/compiler_final_haskell.dir/build
.PHONY : compiler_final_haskell/fast

HCondition.o: HCondition.cpp.o

.PHONY : HCondition.o

# target to build an object file
HCondition.cpp.o:
	$(MAKE) -f CMakeFiles/compiler_final_haskell.dir/build.make CMakeFiles/compiler_final_haskell.dir/HCondition.cpp.o
.PHONY : HCondition.cpp.o

HCondition.i: HCondition.cpp.i

.PHONY : HCondition.i

# target to preprocess a source file
HCondition.cpp.i:
	$(MAKE) -f CMakeFiles/compiler_final_haskell.dir/build.make CMakeFiles/compiler_final_haskell.dir/HCondition.cpp.i
.PHONY : HCondition.cpp.i

HCondition.s: HCondition.cpp.s

.PHONY : HCondition.s

# target to generate assembly for a file
HCondition.cpp.s:
	$(MAKE) -f CMakeFiles/compiler_final_haskell.dir/build.make CMakeFiles/compiler_final_haskell.dir/HCondition.cpp.s
.PHONY : HCondition.cpp.s

HExpression.o: HExpression.cpp.o

.PHONY : HExpression.o

# target to build an object file
HExpression.cpp.o:
	$(MAKE) -f CMakeFiles/compiler_final_haskell.dir/build.make CMakeFiles/compiler_final_haskell.dir/HExpression.cpp.o
.PHONY : HExpression.cpp.o

HExpression.i: HExpression.cpp.i

.PHONY : HExpression.i

# target to preprocess a source file
HExpression.cpp.i:
	$(MAKE) -f CMakeFiles/compiler_final_haskell.dir/build.make CMakeFiles/compiler_final_haskell.dir/HExpression.cpp.i
.PHONY : HExpression.cpp.i

HExpression.s: HExpression.cpp.s

.PHONY : HExpression.s

# target to generate assembly for a file
HExpression.cpp.s:
	$(MAKE) -f CMakeFiles/compiler_final_haskell.dir/build.make CMakeFiles/compiler_final_haskell.dir/HExpression.cpp.s
.PHONY : HExpression.cpp.s

HFunction.o: HFunction.cpp.o

.PHONY : HFunction.o

# target to build an object file
HFunction.cpp.o:
	$(MAKE) -f CMakeFiles/compiler_final_haskell.dir/build.make CMakeFiles/compiler_final_haskell.dir/HFunction.cpp.o
.PHONY : HFunction.cpp.o

HFunction.i: HFunction.cpp.i

.PHONY : HFunction.i

# target to preprocess a source file
HFunction.cpp.i:
	$(MAKE) -f CMakeFiles/compiler_final_haskell.dir/build.make CMakeFiles/compiler_final_haskell.dir/HFunction.cpp.i
.PHONY : HFunction.cpp.i

HFunction.s: HFunction.cpp.s

.PHONY : HFunction.s

# target to generate assembly for a file
HFunction.cpp.s:
	$(MAKE) -f CMakeFiles/compiler_final_haskell.dir/build.make CMakeFiles/compiler_final_haskell.dir/HFunction.cpp.s
.PHONY : HFunction.cpp.s

HLogical.o: HLogical.cpp.o

.PHONY : HLogical.o

# target to build an object file
HLogical.cpp.o:
	$(MAKE) -f CMakeFiles/compiler_final_haskell.dir/build.make CMakeFiles/compiler_final_haskell.dir/HLogical.cpp.o
.PHONY : HLogical.cpp.o

HLogical.i: HLogical.cpp.i

.PHONY : HLogical.i

# target to preprocess a source file
HLogical.cpp.i:
	$(MAKE) -f CMakeFiles/compiler_final_haskell.dir/build.make CMakeFiles/compiler_final_haskell.dir/HLogical.cpp.i
.PHONY : HLogical.cpp.i

HLogical.s: HLogical.cpp.s

.PHONY : HLogical.s

# target to generate assembly for a file
HLogical.cpp.s:
	$(MAKE) -f CMakeFiles/compiler_final_haskell.dir/build.make CMakeFiles/compiler_final_haskell.dir/HLogical.cpp.s
.PHONY : HLogical.cpp.s

Parser.o: Parser.cpp.o

.PHONY : Parser.o

# target to build an object file
Parser.cpp.o:
	$(MAKE) -f CMakeFiles/compiler_final_haskell.dir/build.make CMakeFiles/compiler_final_haskell.dir/Parser.cpp.o
.PHONY : Parser.cpp.o

Parser.i: Parser.cpp.i

.PHONY : Parser.i

# target to preprocess a source file
Parser.cpp.i:
	$(MAKE) -f CMakeFiles/compiler_final_haskell.dir/build.make CMakeFiles/compiler_final_haskell.dir/Parser.cpp.i
.PHONY : Parser.cpp.i

Parser.s: Parser.cpp.s

.PHONY : Parser.s

# target to generate assembly for a file
Parser.cpp.s:
	$(MAKE) -f CMakeFiles/compiler_final_haskell.dir/build.make CMakeFiles/compiler_final_haskell.dir/Parser.cpp.s
.PHONY : Parser.cpp.s

Token.o: Token.cpp.o

.PHONY : Token.o

# target to build an object file
Token.cpp.o:
	$(MAKE) -f CMakeFiles/compiler_final_haskell.dir/build.make CMakeFiles/compiler_final_haskell.dir/Token.cpp.o
.PHONY : Token.cpp.o

Token.i: Token.cpp.i

.PHONY : Token.i

# target to preprocess a source file
Token.cpp.i:
	$(MAKE) -f CMakeFiles/compiler_final_haskell.dir/build.make CMakeFiles/compiler_final_haskell.dir/Token.cpp.i
.PHONY : Token.cpp.i

Token.s: Token.cpp.s

.PHONY : Token.s

# target to generate assembly for a file
Token.cpp.s:
	$(MAKE) -f CMakeFiles/compiler_final_haskell.dir/build.make CMakeFiles/compiler_final_haskell.dir/Token.cpp.s
.PHONY : Token.cpp.s

Tokenizer.o: Tokenizer.cpp.o

.PHONY : Tokenizer.o

# target to build an object file
Tokenizer.cpp.o:
	$(MAKE) -f CMakeFiles/compiler_final_haskell.dir/build.make CMakeFiles/compiler_final_haskell.dir/Tokenizer.cpp.o
.PHONY : Tokenizer.cpp.o

Tokenizer.i: Tokenizer.cpp.i

.PHONY : Tokenizer.i

# target to preprocess a source file
Tokenizer.cpp.i:
	$(MAKE) -f CMakeFiles/compiler_final_haskell.dir/build.make CMakeFiles/compiler_final_haskell.dir/Tokenizer.cpp.i
.PHONY : Tokenizer.cpp.i

Tokenizer.s: Tokenizer.cpp.s

.PHONY : Tokenizer.s

# target to generate assembly for a file
Tokenizer.cpp.s:
	$(MAKE) -f CMakeFiles/compiler_final_haskell.dir/build.make CMakeFiles/compiler_final_haskell.dir/Tokenizer.cpp.s
.PHONY : Tokenizer.cpp.s

generator.o: generator.cpp.o

.PHONY : generator.o

# target to build an object file
generator.cpp.o:
	$(MAKE) -f CMakeFiles/compiler_final_haskell.dir/build.make CMakeFiles/compiler_final_haskell.dir/generator.cpp.o
.PHONY : generator.cpp.o

generator.i: generator.cpp.i

.PHONY : generator.i

# target to preprocess a source file
generator.cpp.i:
	$(MAKE) -f CMakeFiles/compiler_final_haskell.dir/build.make CMakeFiles/compiler_final_haskell.dir/generator.cpp.i
.PHONY : generator.cpp.i

generator.s: generator.cpp.s

.PHONY : generator.s

# target to generate assembly for a file
generator.cpp.s:
	$(MAKE) -f CMakeFiles/compiler_final_haskell.dir/build.make CMakeFiles/compiler_final_haskell.dir/generator.cpp.s
.PHONY : generator.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... compiler_final_haskell"
	@echo "... edit_cache"
	@echo "... HCondition.o"
	@echo "... HCondition.i"
	@echo "... HCondition.s"
	@echo "... HExpression.o"
	@echo "... HExpression.i"
	@echo "... HExpression.s"
	@echo "... HFunction.o"
	@echo "... HFunction.i"
	@echo "... HFunction.s"
	@echo "... HLogical.o"
	@echo "... HLogical.i"
	@echo "... HLogical.s"
	@echo "... Parser.o"
	@echo "... Parser.i"
	@echo "... Parser.s"
	@echo "... Token.o"
	@echo "... Token.i"
	@echo "... Token.s"
	@echo "... Tokenizer.o"
	@echo "... Tokenizer.i"
	@echo "... Tokenizer.s"
	@echo "... generator.o"
	@echo "... generator.i"
	@echo "... generator.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

